// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksLookup.Models;

namespace Parks_Lookup.Migrations
{
    [DbContext(typeof(ParksLookupContext))]
    partial class ParksLookupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksLookup.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Lat")
                        .HasColumnType("double");

                    b.Property<double>("Lng")
                        .HasColumnType("double");

                    b.Property<string>("ParkCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("State")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Zipcode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            City = "Springdale",
                            CreatedDate = new DateTime(2022, 8, 19, 14, 35, 3, 733, DateTimeKind.Local).AddTicks(1687),
                            Description = "Follow the paths where native people and pioneers walked. Gaze up at massive sandstone cliffs of cream, pink, and red that soar into a brilliant blue sky. Experience wilderness in a narrow slot canyon. Zion’s unique array of plants and animals will enchant you as you absorb the rich history of the past and enjoy the excitement of present day adventures.",
                            Lat = 37.298392540000002,
                            Lng = -113.0265138,
                            ParkCode = "zion",
                            State = "UT",
                            Title = "Zion National Park",
                            Zipcode = "84767"
                        },
                        new
                        {
                            ParkId = 2,
                            City = "Bar Harbor",
                            CreatedDate = new DateTime(2022, 8, 19, 14, 35, 3, 733, DateTimeKind.Local).AddTicks(3870),
                            Description = "Acadia National Park protects the natural beauty of the highest rocky headlands along the Atlantic coastline of the United States, an abundance of habitats, and a rich cultural heritage. At 4 million visits a year, it's one of the top 10 most-visited national parks in the United States. Visitors enjoy 27 miles of historic motor roads, 158 miles of hiking trails, and 45 miles of carriage roads.",
                            Lat = 44.409286000000002,
                            Lng = -68.247501,
                            ParkCode = "acad",
                            State = "ME",
                            Title = "Acadia National Park",
                            Zipcode = "04609"
                        },
                        new
                        {
                            ParkId = 3,
                            City = "Crater Lake",
                            CreatedDate = new DateTime(2022, 8, 19, 14, 35, 3, 733, DateTimeKind.Local).AddTicks(3885),
                            Description = "Crater Lake inspires awe. Native Americans witnessed its formation 7,700 years ago, when a violent eruption triggered the collapse of a tall peak. Scientists marvel at its purity—fed by rain and snow, it’s the deepest lake in the USA and one of the most pristine on Earth. Artists, photographers, and sightseers gaze in wonder at its blue water and stunning setting atop the Cascade Mountain Range.",
                            Lat = 42.940658540000001,
                            Lng = -122.13384139999999,
                            ParkCode = "crla",
                            State = "OR",
                            Title = "Crater Lake National Park",
                            Zipcode = "97604"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
